// Code generated by schema-generate. DO NOT EDIT.

package structs

// NFVAdvancedPackageDescriptorSchema The NFV advanced package descriptor schema specifies
// the structure  of the package descriptor. It makes sure
// the relevant information is provided to parse the package
// in a meaningful way.
// 
type PackageDescriptor struct {
  Description string `yaml:"description,omitempty"`
  DescriptorSchema string `yaml:"descriptor_schema"`
  Logo string `yaml:"logo,omitempty"`
  Maintainer string `yaml:"maintainer,omitempty"`
  Name string `yaml:"name"`
  PackageContent []*PackageContent `yaml:"package_content,omitempty"`
  PackageType string `yaml:"package_type,omitempty"`
  ReleaseDateTime string `yaml:"release_date_time,omitempty"`
  Vendor string `yaml:"vendor"`
  Version string `yaml:"version"`
}

// PackageContent 
type PackageContent struct {
  Algorithm string `yaml:"algorithm"`
  ContentType string `yaml:"content-type"`
  Hash string `yaml:"hash"`
  Source string `yaml:"source"`
  Tags []string `yaml:"tags,omitempty"`
}
